---
# Install packages

- name: Install zsh and git
  package:
    name: "{{ general_packages }}"
    state: latest

# Zsh and related stuff

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

- name: Set zsh as default shell
  shell: chsh -s $(which zsh)

- name: Get Powerlevel10k for Zsh
  git:
    repo: https://github.com/romkatv/powerlevel10k
    dest: ~/.oh-my-zsh/custom}/themes/powerlevel10k
    update: yes

- name: Set .zshrc template
  template:
    src: zshrc.template
    dest: ~/.zshrc

# Tmux and related stuff

- name: Get oh-my-tmux template
  git:
    repo: https://github.com/gpakosz/.tmux
    dest: ~/.tmux
    update: yes

- name: Create link to tmux config file
  shell: ln -s -f ~/.tmux/.tmux.conf

- name: Copy tmux local config file
  shell: cp ~/.tmux/.tmux.conf.local .